services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - redis-network

volumes:
  redis-data:
    driver: local

networks:
  redis-network:
    driver: bridge
